thingspeak-modified/config/routes.rb
Thingspeak::Application.routes.draw do

  # admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # main data posts using this route
  match 'update', :to => 'channels#post_data', :via => ((GET_SUPPORT) ? [:get, :post] : :post)
  match 's/update', :to => 'channels#post_data', :via => [:get, :post]

  #feedweather routing
  match 'fw/update', :to  => 'channels#post_data_fw', :via => ((GET_SUPPORT) ? [:get, :post] : :post)


  # handle subdomain routes
  get '/', :to => 'subdomains#index', :constraints => { :subdomain => 'api' }
  get 'crossdomain', :to => 'subdomains#crossdomain', :constraints => { :subdomain => 'api' }

  root :to => 'pages#home'

  # for api: login and get token
  match 'users/api_login', :to => 'users#api_login', :via => [:get, :post]

  # devise for authentication
  # override devise controllers and use custom sessions_controller and registrations_controller
  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  resource :pages do
    collection do
      get :home
      get :about
      get :headers
      get :social_home
      post :contact_us
    end
  end

  match 'users/reset_password/:id', :to => 'users#reset_password', :as => 'reset_password', :via => [:get, :post]
  patch 'users/change_password/:id', :to => 'users#change_password'
  post 'mailer/resetpassword', :to => 'mailer#resetpassword'

  # public user profiles
  match 'account/edit_profile' => 'users#edit_profile', :as => 'edit_profile', :via => [:get, :post]
  patch 'account/update_profile' => 'users#update_profile', :as => 'update_profile'
  # users paths
  post 'users/new_api_key' => 'users#new_api_key', :as => 'user_new_api_key'
  get 'users/:id/channels(.:format)' => 'users#list_channels', :as => 'list_channels', :constraints => { :id => /.*/ }
  get 'users/:glob' => 'users#profile', :as => 'user_profile', :constraints => { :glob => /.*/ }

  resource :user_session
  resource 'account', :to => 'users'
  resources :users

  # social channels
  get 's/' => 'pages#social_home'
  get 's/:slug' => 'channels#social_show', :constraints => { :slug => /.*/ }
  get 'channels/social_new' => 'channels#social_new'

  # search
  resources :tags

  # specific feeds
  get 'channels/:channel_id/feed(s)(.:format)' => 'feed#index'
  get 'channels/:channel_id/field/:field_id(.:format)' => 'feed#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fields/:field_id(.:format)' => 'feed#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/field/:field_id/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fields/:field_id/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/feed(s)/last_average(.:format)' => 'feed#last_average'
  get 'channels/:channel_id/feed(s)/last_median(.:format)' => 'feed#last_median'
  get 'channels/:channel_id/feed(s)/last_sum(.:format)' => 'feed#last_sum'
  get 'channels/:channel_id/feed/entry/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/feeds/entry/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/social_feed' => 'channels#social_feed'
  get 'channels/:channel_id/feed(s)/debug' => 'feed#debug'
  delete 'channels/:id/feeds' => 'channels#clear'

  # feeds for feedweather
  get 'channels/:channel_id/fw/feed(s)(.:format)' => 'feedsweather#index'
  get 'channels/:channel_id/fw/field/:field_id(.:format)' => 'feedsweather#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fw/fields/:field_id(.:format)' => 'feedsweather#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fw/field/:field_id/:id(.:format)' => 'feedsweather#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fw/fields/:field_id/:id(.:format)' => 'feedsweather#show' # not sure why this doesn't work with (s)

  # maps
  get 'channels/:channel_id/maps/channel_show' => 'maps#channel_show'
  get 'channels/:channel_id/status/recent' => 'status#recent'

  # multiple series on a chart demo
  get 'charts/multiple_series' => 'charts#multiple_series'

  # nest the following controllers inside channels
  resources :channels do
    collection do
      get :public
      get :watched
      get :realtime
    end
    member do
      get :import
      post :upload
      post :clear
      put :watch
      post :realtime_update
    end
    resources :feed

    resources :feeds, :to => 'feed'
    resources :api_keys, :except => [:show, :edit]
    resources :status
    resources :statuses, :to => 'status'
    resources :charts
    resources :maps
    resources :channels
    resources :tags
    resources :comments
    resources :windows, :only => [:index, :update] do
      member do
        get :iframe
        get :html
        put :hide
        put :display
      end
    end
  end

  get 'channels/:channel_id/private_windows' => 'windows#private_windows'
  get 'channels/:channel_id/hidden_windows' => 'windows#hidden_windows'
  match 'channels/:channel_id/windows' => 'windows#update', :via => [:post, :put]

  resources :comments do
    member do
      post :vote
    end
  end

  resources :plugins do
    collection do
      get 'private_plugins'
      get 'public_plugins'
      #get 'public'
    end
  end

  resources :devices do
    member do
      get :thingtweet_arduino_code
      get :thingtweet_arduino_select_thingtweet
      post :add_mac_address
      put :ajax_update
    end
  end

  resources :pipes

  # twitter status update (version 1)
  match 'apps/thingtweet/1/statuses/update(.:format)' => 'thingtweets#update', :via => [:get, :post]
  match 'apps/thingtweet/1/statuses/update_debug(.:format)' => 'thingtweets#update_debug', :via => [:get, :post]


  # thinghttp action
  match 'apps/thinghttp/send_request' => 'thinghttp#send_request', :via => [:get, :post]

  # process responses for tweetcontrol
  match 'apps/tweetcontrol/process_response' => 'tweetcontrol#process_response', :via => [:get, :post]

  # apps and nested controllers
  scope 'apps' do
    resources :thingtweets do
      collection do
        get :authorize_response
      end
      member do
        put :new_api_key
      end
    end
    resources :thinghttp do
      resources :header
      member do
        put :new_api_key
      end
    end
    resources :talkbacks do
      member do
        put :new_api_key
      end
    end
    resources :tweetcontrol
    resources :reacts
    resources :timecontrols
  end

  # talkback api
  delete 'talkbacks/:talkback_id/commands', :to => 'commands#destroy_all'
  delete 'talkbacks/:talkback_id/commands/destroy_all', :to => 'commands#destroy_all'
  resources :talkbacks do
    resources :commands do
      collection do
        match :execute, :via => [:post, :get]
        delete :destroy_all
      end
    end
  end

  resources :apps, :only => ['index']

  # admin signups by day
  get 'admin/signups', :as => 'admin_signups', :to => 'admin/users#signups'
  # admin list of all email addresses
  get 'admin/emails', :as => 'admin_emails', :to => 'admin/users#emails'

  # app shortcuts
  get 'apps/thingtweet', :to => 'thingtweets#index'
  get 'apps/react', :to => 'react#index'

  # docs
  get 'docs(/:action)', :to => 'docs'

  # users
  devise_scope :user do
    match 'login', to: "devise/sessions#new", :via => [:get, :post]
    match 'logout', to: "devise/sessions#destroy", :via => [:get, :post]
  end

  # streaming routes
  match '/stream/channels/:id/feeds(.:format)', to: 'stream#channel_feed', :via => [:get, :post]

  # add support for CORS preflighting (matches any OPTIONS route up to 5 levels deep)
  # examples: /talkbacks, /talkbacks/4, /talkbacks/4/commands, /talkbacks/4/commands/6, /apps/thingtweet/1/statuses/update
  match '/:foo(/:foo(/:foo(/:foo(/:foo))))', :to => 'cors#preflight', :via => 'options'

  #match ':controller(/:action(/:id(.:format)))', :via => :all
end

thingspeak-modified/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include KeyUtilities
  skip_before_filter :verify_authenticity_token, :only => [:api_login]
  before_filter :require_user, :only => [:show, :edit, :update, :edit_profile]

  # delete account
  def destroy
    user = current_user
    user.delete
    flash[:notice] = t(:account_deleted)
    redirect_to root_path
  end

  # allow login via api
  def api_login
    # get the user by login or email
    user = User.find_by_login_or_email(params[:login])

    # exit if no user or invalid password
    respond_with_error(:error_auth_required) and return if user.blank? || !user.valid_password?(params[:password])

    # save new authentication token
    if user.authentication_token.blank?
      user.authentication_token = Devise.friendly_token
      user.save
    end

    # output the user with token
    respond_to do |format|
      format.json { render :json => user.as_json(User.private_options_plus(:authentication_token)) }
      format.xml { render :xml => user.to_xml(User.private_options_plus(:authentication_token)) }
      format.any { render :text => user.authentication_token }
    end
  end

  # generates a new api key
  def new_api_key
    current_user.set_new_api_key!
    redirect_to account_path
  end

  # edit public profile
  def edit_profile
    @user = current_user
  end

  # update public profile
  def update_profile
    @user = current_user # makes our views "cleaner" and more consistent
    # update
    @user.update_attributes(user_params)
    redirect_to account_path
  end

  # public profile for a user
  def profile
    # set params and request.format correctly
    set_request_details!(params)

    @user = User.find_by_login(params[:id])

    # output error if user not found
    render :text => t(:user_not_found) and return if @user.nil?

    # set page title
    @title = @user.login || nil

    # if a json or xml request
    if request.format == :json || request.format == :xml
      # authenticate the user if the user is logged in (can be via token) or api key matches the target user
      authenticated = (current_user == @user) || (User.find_by_api_key(get_apikey) == @user)
      # set options correctly
      options = authenticated ? User.private_options : User.public_options(@user)
    end

    # if html request
    if request.format == :html
      @channels = @user.channels.public_viewable.paginate :page => params[:page], :order => 'last_entry_id DESC'
    end

    respond_to do |format|
      format.html
      format.json { render :json => @user.as_json(options) }
      format.xml { render :xml => @user.to_xml(options) }
    end
  end

  # list all public channels for a user
  def list_channels
    @user = User.find_by_login(params[:id])

    # output error if user not found
    render :text => t(:user_not_found) and return if @user.nil?

    # if html request
    if request.format == :html
      @title = "Internet of Things - Public Channels for #{@user.login}"
      @channels = @user.channels.public_viewable.paginate :page => params[:page], :order => 'last_entry_id DESC'
    # if a json or xml request
    elsif request.format == :json || request.format == :xml
      # authenticate the user if api key matches the target user
      authenticated = (User.find_by_api_key(get_apikey) == @user)
      # get all channels if authenticated, otherwise only public ones
      channels = authenticated ? @user.channels : @user.channels.public_viewable
      # set channels correctly
      @channels = { channels: channels.as_json(Channel.public_options) }
    end

    respond_to do |format|
      format.html
      format.json { render :json => @channels }
      format.xml { render :xml => @channels.to_xml(:root => 'response') }
    end
  end

  def show
    @menu = 'account'
    @user = @current_user
  end

  def edit
    @menu = 'account'
    @user = @current_user
  end

  def update
    @menu = 'account'
    @user = @current_user # makes our views "cleaner" and more consistent

    # delete password and confirmation from params if not present
    params[:user].delete(:password) if params[:user][:password].blank?

    # check current password and update
    if @user.valid_password?(params[:user][:password_current]) && @user.update_attributes(user_params)
      # sign the user back in, since devise will log the user out on update
      sign_in(current_user, :bypass => true)
      flash[:notice] = t('devise.registrations.updated')
      redirect_to account_path
    else
      @user.errors.add(:base, t(:password_incorrect))
      render :action => :edit
    end
  end

  private

    # only allow these params
    def user_params
      params.require(:user).permit(:email, :login, :time_zone, :public_flag, :bio, :website, :password, :password_confirmation)
    end

    # set params[:id] and request.format correctly
    def set_request_details!(params)
      # set format
      new_format = 'html' if params[:glob].end_with?('.html')
      new_format = 'json' if params[:glob].end_with?('.json')
      new_format = 'xml' if params[:glob].end_with?('.xml')

      # remove the format from the end of the glob
      params[:id] = params[:glob].chomp(".#{new_format}")

      # set the new format if it exists
      request.format = new_format.to_sym if new_format.present?
    end

end

thingspeak-modified/app/helpers/users_helper.rb
module UsersHelper
end

thingspeak-modified/app/views/users/_list_channels.html.erb
<h3><%= t(:user_public_channels) %> <%= @user.login %></h3>

<% if @channels.present? && @channels.count > 0 %>
  <table class="table table-striped table-bordered  tablesorter" data-no-turbolink>
    <thead>
      <tr>
        <th class="col-sm-5 col-xs-5"><%= t(:channel_name) %> <i class="fa fa-unsorted"></i></th>
        <th class="col-sm-5 col-xs-5"><%= t(:channel_description) %> <i class="fa fa-unsorted"></i></td>
        <th class="col-sm-2 col-xs-2"><%= t(:tags) %> <i class="fa fa-unsorted"></i></td>
      </tr>
    </thead>
    <tbody>

      <% @channels.each do |channel| %>
        <tr>
          <td>
            <h4 style="margin-top: 0;">
              <%= link_to channel.name, channel_path(channel.id) %>
            </h4>
            <%= link_to T(:view), channel_path(channel.id), class: 'btn btn-default btn-sm' %>
          <td><%= channel.description %></td>
          <td>
            <% channel.tags.each do |tag| %>
              <a href="/channels/public?tag=<%=u tag.name %>"><%= tag.name %></a><% unless tag == channel.tags.last %>, <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
  <br>
  <%= will_paginate @channels, renderer: BootstrapPagination::Rails %>
<% else %>
  <%= t(:user_no_public_channels) %>
<% end %>

thingspeak-modified/app/views/users/_login.html.erb
<%= form_for @user_session, :url => user_session_path, :html => { :id => 'loginform' } do |f| %>
	<input name='userlogin' class='userlogin' />
	<%= f.hidden_field :remember_me, :value => false %>
	<table id="login" class="round">
		<tr>
			<td colspan="2" class="text_center">
				<%= t(:secure_signin) %>
			</td>
		</tr>
		<tr>
			<td class="login_info"><%= t(:userid) %></td>
			<td><%= f.text_field :login, :size => 15, :value => cookies['user_id'] %></td>
		</tr>
		<tr>
			<td class="login_info"><%= t(:password) %></td>
			<td><%= f.password_field :password, :size => 15 %></td>
		</tr>
		<tr>
			<td class="login_info"><%= f.check_box :remember_id, :checked => true %></td>
			<td class="small"><%= t(:remember_me) %></td>
		</tr>
		<tr>
			<td></td>
			<td><%= link_to t(:forgot), forgot_password_users_path, :id => 'forgot_password' %></td>
		</tr>
		<tr>
			<td></td>
			<td><%= f.submit t(:signin) %></td>
		</tr>
	</table>
<% end %>
<script type="text/javascript">
	var login = document.getElementById('user_session_login');
	if (login.value.length == 0)
		login.focus();
	else
		document.getElementById('user_session_password').focus();
</script>

thingspeak-modified/app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-xs-7">

    <ol class="breadcrumb">
      <li><%= link_to t(:myaccount), account_path %></li>
      <li class="active"><%= t(:account_edit) %></li>
    </ol>

    <div class="col-pad">
      <%= form_for @user, :url => account_path, :html => {:class => 'form-horizontal'} do |f| %>
        <%= error_messages_for 'user', :header_message => t(:try_again), :message => t(:account_error_edit) %>
        <input name='userlogin' class='userlogin' />

        <div class="form-group">
          <label class="col-sm-4 col-xs-4 control-label"><%= t(:userid) %></label>
          <div class="col-sm-8 col-xs-8"><%= f.text_field :login, :class => 'form-control' %></div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 col-xs-4 control-label"><%= t(:email) %></label>
          <div class="col-sm-8 col-xs-8"><%= f.text_field :email, :class => 'form-control' %></div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 col-xs-4 control-label"><%= t(:time_zone) %></label>
          <div class="col-sm-8 col-xs-8">
            <p class="form-control-static">
              <%= time_zone_select 'user', 'time_zone', nil, {:default => 'Eastern Time (US & Canada)'}, {:class => 'form-control'} %>
            </p>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 col-xs-4 control-label"><%= t(:password_change) %></label>
          <div class="col-sm-8 col-xs-8"><%= f.password_field :password, :class => 'form-control' %></div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 col-xs-4 control-label"><%= t(:password_current) %></label>
          <div class="col-sm-8 col-xs-8"><%= f.password_field :password_current, :class => 'form-control' %></div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-8 col-xs-offset-4 col-xs-8"><p class="form-control-static"><%= f.submit t(:account_update), :class => 'btn btn-primary' %></p></div>
        </div>

      <% end %>

    </div>
  </div>
</div>

<br><br>

<h3><%= t(:account_delete_message) %></h3>
<%= button_to t(:account_delete), user_path(@user.id), :method => 'delete', :data => { :confirm => t(:confirm_account_delete) }, :class => 'btn btn-danger' %>

thingspeak-modified/app/views/users/edit_profile.html.erb
<div class="col-sm-8 col-xs-7">

  <ol class="breadcrumb">
    <li><%= link_to t(:myaccount), account_path %></li>
    <li class="active"><%= t(:profile_edit) %></li>
  </ol>

  <div class="col-pad">
    <%= form_for @user, :url => update_profile_path, :html => {:class => 'form-horizontal'} do |f| %>
      <input name='userlogin' class='userlogin' />

      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8 col-xs-offset-3 col-xs-6">
          <div class="checkbox">
            <label>
              <%= f.check_box :public_flag %>
              <%= t(:public) %>
            </label>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 col-xs-3 control-label"><%= t(:profile_website) %></label>
        <div class="col-sm-8 col-xs-6"><%= f.text_field :website, :class => 'form-control' %></div>
      </div>


      <div class="form-group">
        <label class="col-sm-4 col-xs-3 control-label"><%= t(:profile_bio) %></label>
        <div class="col-sm-8 col-xs-6"><%= f.text_area :bio, :class => 'form-control', :rows => 4 %></div>
      </div>


      <div class="form-group">
        <label class="col-sm-4 control-label"></label>
        <div class="col-sm-8"><p class="form-control-static"><%= f.submit t(:profile_update), :class => 'btn btn-primary' %></p></div>
      </div>

    <% end %>

  </div>
</div>

thingspeak-modified/app/views/users/forgot_password.html.erb
<div class="col-sm-7 col-xs-12">

  <h4 class="breadcrumb"><%= t(:password_forgot) %></h4>

  <%= t(:password_forgot_message) %>

  <br><br>

  <%= form_for @user, :url => { :controller => 'mailer', :action => 'resetpassword' }, :html => {:class => 'form-horizontal' } do |f| %>
    <input name='userlogin' class='userlogin' />

    <div class="form-group">
      <label class="col-sm-3 col-xs-3 control-label"><%= t(:email) %></label>
      <div class="col-sm-9 col-xs-9"><%= f.text_field :login, :class => 'form-control' %></div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-9 col-xs-offset-3 col-xs-9"><p class="form-control-static"><%= f.submit t(:submit), :class => 'btn btn-primary' %></p></div>
    </div>

  <% end %>

</div>


<script type="text/javascript">
  document.getElementById('user_login').focus();
</script>

thingspeak-modified/app/views/users/list_channels.html.erb
<%= render 'list_channels' %>

thingspeak-modified/app/views/users/new.html.erb
<div class="col-sm-8 col-xs-7">

  <h4 class="breadcrumb"><%= t(:signup_header) %></h4>

  <%= form_for @user, :url => account_path, :html => {:class => 'form-horizontal'} do |f| %>
    <%= error_messages_for 'user', :header_message => t(:try_again), :message => t(:account_error) %>
    <input name='userlogin' class='userlogin' />

    <div class="form-group">
      <label class="col-sm-4 col-xs-3 control-label"><%= t(:userid) %></label>
      <div class="col-sm-8 col-xs-6"><%= f.text_field :login, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 col-xs-3 control-label"><%= t(:email) %></label>
      <div class="col-sm-8 col-xs-6"><%= f.text_field :email, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 col-xs-3 control-label"><%= t(:time_zone) %></label>
      <div class="col-sm-8 col-xs-8">
        <p class="form-control-static">
          <%= time_zone_select 'user', 'time_zone', nil, {:default => 'Eastern Time (US & Canada)'}, {:class => 'form-control'} %>
        </p>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 col-xs-3 control-label"><%= t(:password) %></label>
      <div class="col-sm-8 col-xs-6"><%= f.password_field :password, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 col-xs-3 control-label"><%= t(:password_confirmation) %></label>
      <div class="col-sm-8 col-xs-6"><%= f.password_field :password_confirmation, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label"></label>
      <div class="col-sm-8"><p class="form-control-static"><%= f.submit t(:create_account), :id => "user_submit", :class => 'btn btn-primary' %></p></div>
    </div>

  <% end %>
</div>

<script type="text/javascript">
  document.getElementById('user_login').focus();
</script>

thingspeak-modified/app/views/users/profile.html.erb
<% if @user.public_flag == true %>

  <div class="FR">
    <br><br>
    <%= gravatar_tag @user, :default => 'wavatar', :secure => true %>
  </div>

  <h2><%= t(:profile_for) %> <%= @user.login %></h2>
  <%= t(:member_since) %> <%= @user.created_at.strftime('%B %-d, %Y') %>
  <br><br>
  <%= t(:profile_website) %>: <%= link_to @user.website, @user.display_website, target: '_blank' %>
  <br><br>
  <%= t(:profile_bio) %>: <%= @user.bio %>
  <br><br>
  <%= render 'list_channels' %>

<% else %>
  <%= t(:profile_not_public) %>
<% end %>

thingspeak-modified/app/views/users/reset_password.html.erb
<% if @valid_link %>
  <h2><%= t(:password_new) %></h2>
  <%= form_for @user, :url => { :controller => 'users', :action => 'change_password', :id => @user.id } do |f| %>
    <%= error_messages_for 'user', :header_message => t(:try_again), :message => t(:password_new_error) %>
    <input name='userlogin' class='userlogin' />
    <table class="bigtable">
      <tr>
        <td class="left">
          <div class="vcenter"><%= f.label :password %></div>
        </td>
        <td class="right">
          <%= f.password_field :password %>
          <br />
          <%= t(:password_new_choose) %>
        </td>
      <tr>
        <td class="left">
          <%= f.label :password_confirmation, raw(t(:password_confirmation)) %>
        </td>
        <td class="right">
          <%= f.password_field :password_confirmation %>
          <br />
          <%= t(:password_new_confirmation) %>
        </td>
      </tr>
      <tr>
        <td class="left"></td>
        <td class="right"><%= f.submit t(:submit) %></td>
      </tr>
    </table>
  <% end %>
<% else %>
  <%= t(:password_link_expired) %>
<% end %>

thingspeak-modified/app/views/users/show.html.erb
<div class="col-sm-5 col-xs-12">

  <h4 class="breadcrumb"><%= t(:myaccount) %></h4>

  <div class="col-pad">
    <%= link_to t(:account_edit), edit_account_path, :class => 'btn btn-primary btn-sm' %>
    <br><br>
    <table class="table">
      <tr>
        <td><%= t(:userid) %></td>
        <td><%= @user.login %></td>
      </tr>
      <tr>
        <td><%= t(:email) %></td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td><%= t(:time_zone) %></td>
        <td><%= @user.time_zone_or_utc %></td>
      </tr>
      <tr>
        <td><%= t(:api_key) %></td>
        <td>
          <code><%= @user.api_key %></code><br><br>
          <%= button_to t(:api_key_new), user_new_api_key_path, :data => { :confirm => t(:confirm_new_user_api_key) }, :class => 'btn btn-warning btn-sm' %>
        </td>
      </tr>

    </table>
  </div>

  <br><br>
  <h4 class="breadcrumb"><%= t(:public_profile) %></h4>
  <div class="col-pad">
    <%= link_to t(:profile_edit), edit_profile_path, :class => 'btn btn-primary btn-sm' %>
    <br><br>
    <%= link_to t(:profile_view), user_profile_path(@user.login) %>
    <br><br>
    <% if @user.public_flag %>
      <table class="table">
        <tr>
          <td><%= t(:profile_website) %></td>
          <td><%= @user.website %></td>
        </tr>
        <tr>
          <td><%= t(:profile_bio) %></td>
          <td><%= @user.bio %></td>
        </tr>
      </table>
    <% else %>
      <%= t(:profile_not_public_me) %>
    <% end %>

  </div>
</div>